[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyctrials"
version = "0.1.10"
authors = [
    { name = "Anass Tinakoua", email = "a.tinakoua@gmail.com" },
]
description = "A Python client for interacting with the ClinicalTrials.gov API v2"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.25.0",
    "pandas>=1.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["pyctrials"]

[tool.hatch.build]
only-packages = true